import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { TrustEngineService } from '../engine/trust-engine.service';

@Injectable()
export class AnalysisService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly trustEngine: TrustEngineService,
  ) {}

  async analyze(signalId: string) {
    const result = await this.trustEngine.analyze(signalId);

    const signal = await this.prisma.signal.findUnique({
      where: {
        id: signalId,
      },
    });

    if (!signal) {
      throw new NotFoundException('Signal not found');
    }

    return this.prisma.analysis.upsert({
      where: {
        signalId,
      },
      update: {
        sourceCount: result.sourceCount,
        credibility: result.credibility,
        contradictions: result.contradictions,
        consensus: result.consensus,
        summary: 'Automatic analysis generated by Trust Engine',
      },
      create: {
        signalId,
        sourceCount: result.sourceCount,
        credibility: result.credibility,
        contradictions: result.contradictions,
        consensus: result.consensus,
        summary: 'Automatic analysis generated by Trust Engine',
      },
    });
  }
}