import { Injectable, NotFoundException } from '@nestjs/common';

import { PrismaService } from '../prisma/prisma.service';
import { TrustEngineService } from '../engine/trust-engine.service';
import { EvidenceService } from '../evidence/evidence.service';

@Injectable()
export class AnalysisService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly trustEngine: TrustEngineService,
    private readonly evidenceService: EvidenceService,
  ) {}

  async analyze(signalId: string) {
    console.log('===================================');
    console.log('Analyse gestartet');
    console.log('SignalId erhalten:', signalId);

    // Alle ersten 5 Signale aus der Datenbank anzeigen
    const allSignals = await this.prisma.signal.findMany({
      take: 5,
      orderBy: {
        createdAt: 'desc',
      },
    });

    console.log('Erste 5 Signale in der Datenbank:');
    console.log(allSignals);

    // Gesuchtes Signal laden
    const signal = await this.prisma.signal.findUnique({
      where: {
        id: signalId,
      },
    });

    console.log('Signal gefunden:');
    console.log(signal);

    if (!signal) {
      throw new NotFoundException('Signal not found');
    }

    // Evidence sammeln
    const evidence = await this.evidenceService.collectEvidence(signalId);

    // Trust berechnen
    const result = await this.trustEngine.analyze(signalId);

    // Analyse speichern
    const analysis = await this.prisma.analysis.upsert({
      where: {
        signalId,
      },
      update: {
        sourceCount: result.sourceCount,
        credibility: result.credibility,
        contradictions: result.contradictions,
        consensus: result.consensus,
        summary: 'Automatic analysis generated by Trust Engine',
      },
      create: {
        signalId,
        sourceCount: result.sourceCount,
        credibility: result.credibility,
        contradictions: result.contradictions,
        consensus: result.consensus,
        summary: 'Automatic analysis generated by Trust Engine',
      },
    });

    return {
      signal,
      heartbeat: {
        score: signal.score,
        priority: signal.priority,
      },
      evidence,
      analysis,
    };
  }
}